on:
  push:
    branches:
      - production 
      - staging
  workflow_dispatch:
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
    - name: Krok 12
      uses: actions/checkout@v1
    - name: Wdrożenie aplikacji do FTP - Krok 2
      uses: SamKirkland/FTP-Deploy-Action@v4.3.3
      with: 
        server: "s1.ct8.pl"
        server-dir: "./"
        username: ${{secrets.FTP_USERNAME}}
        password: ${{secrets.FTP_PASSWORD}}
      
  
  
